# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        brew install python 
        brew install pyqt@5
        brew install poppler-qt5
        brew install poppler
        # sudo apt install python3-poppler-qt5 python3-pyqt5
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller 
        # pip install -r requirements.txt
        git  clone https://github.com/frescobaldi/python-poppler-qt5
        cd python-poppler-qt5
        python -m pip install .
        cd ../
    - name: Build package
      run: |
        pyinstaller pyinstaller_build.py -w --noconfirm  --additional-hooks-dir=hooks --hidden-import PyQt5.QtXml --name="darshak" --onefile
        echo ${{ github.sha }} > Release.txt
        mv dist/darshak  dist/darshak-mac
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        path: dist/darshak-mac
    # Build windows image
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release.txt
          LICENSE
          dist/darshak-mac
